# Use official image, so it can be used on Intel PCs, Apple Silicon (M1) and Raspberry Pi's
FROM python:3.9-slim-buster

WORKDIR /code
RUN python -m pip install --upgrade pip

COPY . /code/
RUN pip install -r requirements.txt

ENTRYPOINT [ "python", "main.py" ]
